{
 "title": "Unicorn Testnet Validator To Be Exported",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"unicorn-testnet\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=\"unicorn-testnet\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=\"unicorn-testnet\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{job=\"unicorn-testnet\"}) /  count(count(node_cpu_seconds_total{job=\"unicorn-testnet\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{job=\"unicorn-testnet\"}) /  count(count(node_cpu_seconds_total{job=\"unicorn-testnet\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"unicorn-testnet\"} * 100) / node_memory_MemTotal_bytes{job=\"unicorn-testnet\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"unicorn-testnet\"} - node_memory_SwapFree_bytes{job=\"unicorn-testnet\"}) / (node_memory_SwapTotal_bytes{job=\"unicorn-testnet\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"unicorn-testnet\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"unicorn-testnet\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"unicorn-testnet\"} - node_boot_time_seconds{job=\"unicorn-testnet\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"unicorn-testnet\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"unicorn-testnet\",device!~'rootfs'} - node_filesystem_avail_bytes{job=\"unicorn-testnet\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"unicorn-testnet\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"unicorn-testnet\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"unicorn-testnet\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"unicorn-testnet\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=\"unicorn-testnet\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=\"unicorn-testnet\"}) by (cpu))",
     "legendFormat": "Busy System"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"unicorn-testnet\"} * 100) / node_memory_MemTotal_bytes{job=\"unicorn-testnet\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"unicorn-testnet\"}[5m])*8)",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"unicorn-testnet\",device=\"/dev/mapper/vg26733-root\"} * 100) / node_filesystem_size_bytes{job=\"unicorn-testnet\",device!~'rootfs'})",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "up{job=\"unicorn-testnet\"}",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=\"unicorn-testnet\"} [1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "VALIDATOR METRICS - HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Tendermint block time 5m avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "300 / delta(tendermint_consensus_latest_block_height{job=\"unicorn-testnet\"}[5m])",
     "legendFormat": "Average block time"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{job=\"unicorn-testnet\"}",
     "legendFormat": "latest_block_height"
    }
   ]
  },
  {
   "title": "Tendermint Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{job=\"unicorn-testnet\"}",
     "legendFormat": "tendermint_p2p_peers"
    }
   ]
  },
  { "title": "BONDED DETAILS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Bonded status",
   "type": "timeseries",
   "description": "1 = yes, bonded",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "bonding_status{job=\"unicorn-testnet\"}",
     "legendFormat": "bonded"
    }
   ]
  },
  {
   "title": "Jailed status",
   "type": "timeseries",
   "description": "1 = yes, bonded",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "jailed_status{job=\"unicorn-testnet\"}",
     "legendFormat": "jailed"
    }
   ]
  },
  {
   "title": "Bonded coins delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[24h])/1e6",
     "legendFormat": "24h"
    },
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[12h])/1e6",
     "legendFormat": "12h"
    },
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[6h])/1e6",
     "legendFormat": "6h"
    },
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[3h])/1e6",
     "legendFormat": "3h"
    },
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[1h])/1e6",
     "legendFormat": "1h"
    },
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[48h])/1e6",
     "legendFormat": "48h"
    },
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[96h])/1e6",
     "legendFormat": "96"
    }
   ]
  },
  {
   "title": "Bonded coins delta 1m > X",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[1m])/1e6 > 50",
     "legendFormat": "50"
    },
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[1m])/1e6 > 100",
     "legendFormat": "100"
    },
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[1m])/1e6 > 200",
     "legendFormat": "200"
    },
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[1m])/1e6 > 500",
     "legendFormat": "500"
    },
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[1m])/1e6 > 1000",
     "legendFormat": "1000"
    },
    {
     "expr": "delta(bonded_tokens{job=\"unicorn-testnet\"}[1m])/1e6 > 2000",
     "legendFormat": "2000"
    }
   ]
  },
  {
   "title": "Bonded coins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "bonded_tokens{job=\"unicorn-testnet\"}/100000",
     "legendFormat": "bonded coins"
    }
   ]
  },
  {
   "title": "Bonded coins increase 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "increase(bonded_tokens{job=\"unicorn-testnet\"}[1h])/1e6",
     "legendFormat": "1h"
    },
    {
     "expr": "increase(bonded_tokens{job=\"unicorn-testnet\"}[1m])/1e6",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "Delegator Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "delegator_count{job=\"unicorn-testnet\"}",
     "legendFormat": "delegators"
    }
   ]
  },
  {
   "title": "Delegator Count - Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "delta(delegator_count{job=\"unicorn-testnet\"}[24h])",
     "legendFormat": "24h"
    },
    {
     "expr": "delta(delegator_count{job=\"unicorn-testnet\"}[12h])",
     "legendFormat": "12h"
    },
    {
     "expr": "delta(delegator_count{job=\"unicorn-testnet\"}[6h])",
     "legendFormat": "6h"
    },
    {
     "expr": "delta(delegator_count{job=\"unicorn-testnet\"}[3h])",
     "legendFormat": "3h"
    },
    {
     "expr": "delta(delegator_count{job=\"unicorn-testnet\"}[1h])",
     "legendFormat": "1h"
    },
    {
     "expr": "delta(delegator_count{job=\"unicorn-testnet\"}[48h])",
     "legendFormat": "48h"
    },
    {
     "expr": "delta(delegator_count{job=\"unicorn-testnet\"}[96h])",
     "legendFormat": "96"
    }
   ]
  },
  { "title": "CHAIN METRICS - MISC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Uncommitted txs in mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "cometbft_mempool_size{job=\"unicorn-testnet\"}",
     "legendFormat": "mempool #txs"
    }
   ]
  },
  {
   "title": "Blocks missed, uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - missed_blocks{job=\"unicorn-testnet\"} / 108000 * 100",
     "legendFormat": "Uptime %"
    },
    {
     "expr": "missed_blocks{job=\"unicorn-testnet\"}",
     "legendFormat": "Blocks missed"
    }
   ]
  }
 ]
}